Repository irivera2116/sports-tracking-app, pull requests merged in 2023-07, with the labels that each got.

#3 initial commit
  .env.EXAMPLE
  README.md
  config/connection.js
  controllers/api/index.js
  controllers/api/projectRoutes.js
  controllers/api/userRoutes.js
  controllers/index.js
  db/schema.sql
  models/index.js
  models/project.js
  models/user.js
  package.json
  public/style.css
  seeds/index.js
  server.js
  utils/auth.js
  views/homepage.handlebars
  views/login.handlebars
  views/main.handlebars
Labels: enhancement

#8 added a userdata.json file in seeds
  seeds/userData.json
Labels: enhancement

#9 Schema
  config/connection.js
  db/schema.sql
Labels: enhancement

#12 created seeds.sql and added code
  db/schema.sql
  db/seed.sql
Labels: enhancement

#13 added seed.js
  seeds/index.js
  seeds/seed.js
Labels: enhancement

#15 user.js
  models/user.js
Labels: enhancement

#17 this is the troubleshooting i did with my tutor
  .env.EXAMPLE
  config/connection.js
  db/schema.sql
  models.2/index.js
  models/project.js
  models/rooms.js
  views/layouts/main.handlebars
Labels: bug

#18 login info completed
  models/login_info.js
Labels: enhancement

#21 Adds in Tailwind-CSS
  package.json
  public/output.css
  public/style.css
  tailwind.config.js
  views/login.handlebars
Labels: enhancement

#22 Try3
  models/login_info.js
  models/messages.js
  models/rooms.js
Labels: enhancement

#24 worked on main js file, models, routes, frontend js
  config/connection.js
  config/orm.js
  controllers/api/socketRoutes
  controllers/index.js
  db/schema.sql
  models/messages.js
  models/project.js
  package.json
  public/javascript/chatroom.js
  public/javascript/index.js
  public/javascript/login.js
  public/javascript/logout.js
  public/javascript/signup.js
  public/javascript/socket.io.js
  public/signup.html
  seeds/login_info.js
  seeds/messages.js
  seeds/rooms.js
  seeds/user.js
  server.js
  views/layouts/main.handlebars
  views/main.handlebars
  views/signup.handlebars
Labels: enhancement

#25 added main.handlebar
  views/layouts/main.handlebars
Labels: enhancement

#27 fixed index in models
  models.2/index.js
  models/index.js
Labels: enhancement

#28 models and socketroutes
  controllers/api/index.js
  controllers/api/socketRoutes
  db/seed.sql
  models/login_info.js
  public/javascript/chatroom.js
Labels: enhancement

#29 Project working
  controllers/api/userRoutes.js
  views/homepage.handlebars
Labels: enhancement

#31 fixed login page
  controllers/homeRoutes.js
Labels: enhancement

#35 handlebars
  controllers/homeRoutes.js
  views/homepage.handlebars
  views/login.handlebars
  views/signup.handlebars
Labels: enhancement

#37 Main HandleBars and Login CSS
  config/connection.js
  controllers/homeRoutes.js
  tailwind.config.js
  views/homepage.handlebars
  views/layouts/main.handlebars
  views/login.handlebars
Labels: enhancement

#38 readME file
  README.md
Labels: enhancement

#40 homepage.css
  views/homepage.handlebars
Labels: enhancement

#41 some public changes
  public/javascript/chatroom.js
  public/javascript/index.js
  public/javascript/login.js
  public/javascript/signup.js
Labels: enhancement

#42 Working main
  controllers/api/scores.js
  controllers/homeRoutes.js
  server.js
  views/homepage.handlebars
Labels: enhancement

#43 Homepage.editing
  views/homepage.handlebars
Labels: enhancement

#44 Registration and Main Updates
  views/homepage.handlebars
  views/layouts/main.handlebars
  views/login.handlebars
  views/signup.handlebars
Labels: enhancement

#46 a whole bunch of changes
  config/connection.js
  config/orm.js
  controllers/api/index.js
  controllers/api/roomRoutes.js
  controllers/api/scores.js
  controllers/api/socketRoutes.js
  controllers/api/userRoutes.js
  controllers/homeRoutes.js
  controllers/index.js
  db/schema.sql
  db/seed.sql
  models/index.js
  models/login_info.js
  models/messages.js
  models/rooms.js
  models/user.js
  package.json
  public/avatars/1.png
  public/avatars/2.png
  public/avatars/3.png
  public/avatars/4.png
  public/avatars/5.png
  public/chatroom.css
  public/javascript/chatroom.js
  public/javascript/index.js
  public/javascript/login.js
  public/javascript/logout.js
  public/javascript/signup.js
  public/signup.css
  routes/apiRoute.js
  routes/socketRoute.js
  server.js
  views/homepage.handlebars
  views/layouts/main.handlebars
  views/login.handlebars
  views/signup.handlebars
Labels: documentation, enhancement

#47 api key scores.js
  models/scores.js
Labels: enhancement

#48 fixed css bug and adjust seed.sql
  db/seed.sql
  views/layouts/main.handlebars
  views/signup.handlebars
Labels: enhancement

#49 Recreated Login Page with functionality
  config/connection.js
  views/layouts/main.handlebars
  views/login.handlebars
Labels: enhancement

#51 still working
  config/connection.js
  views/homepage.handlebars
Labels: enhancement

#52 fixed signup hbs and created route for score api and adjusted server.…
  config/connection.js
  routes/scoreRoute.js
  server.js
  views/signup.handlebars
Labels: enhancement

#53 working on it
  config/connection.js
  public/javascript/chatroom.js
  views/homepage.handlebars
Labels: enhancement

#55 added favicon
  config/connection.js
  models/scores.js
  public/android-chrome-192x192.png
  public/android-chrome-512x512.png
  public/apple-touch-icon.png
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon.ico
Labels: enhancement
